#!/bin/sh
# GL-MT6000 首次启动个性化设置


# ============================================================
# 系统
# ============================================================

uci -q batch <<-EOF
	set system.@system[0].hostname='GLMT6000_28'
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'
	set system.@system[0].ttylogin='0'
	set system.@system[0].log_size='128'
	set system.@system[0].urandom_seed='0'

	delete system.ntp
	set system.ntp=timeserver
	set system.ntp.enabled='1'
	set system.ntp.enable_server='0'

	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp.aliyun.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='ntp.tuna.tsinghua.edu.cn'

	commit system
EOF


# ============================================================
# root 默认密码
#
# 密码：admin
# MD5-crypt 哈希必须使用单引号，
# 避免 shell 把 $ 符号展开。
# ============================================================

sed -i \
	's|^root:[^:]*:|root:$1$Op3nWrtX$l7bDHUU8J8QiMrMHTsaL51:|' \
	/etc/shadow


# ============================================================
# GL-MT6000 默认无线
#
# 2.4G：
#   SSID       IMZLY-2G
#
# 5G：
#   SSID       IMZLY-5G
#
# 加密：
#   WPA2-PSK
#   AES / CCMP
#
# 密码：
#   ljx2026@.
# ============================================================


# 如果无线配置尚未生成，先生成
[ -f /etc/config/wireless ] || /sbin/wifi config


# OpenWrt 配置函数
. /lib/functions.sh


# WiFi 密码
WIFI_KEY='ljx2026@.'


# ============================================================
# 启用无线设备
# ============================================================

set_radio() {

	local radio="$1"

	uci -q delete wireless.$radio.disabled
}


# ============================================================
# 根据无线频段设置 SSID / WPA2-PSK / 密码
# ============================================================

set_iface() {

	local iface="$1"
	local device
	local band
	local ssid


	config_get device "$iface" device

	[ -n "$device" ] || return 0


	band=$(uci -q get wireless.$device.band)


	case "$band" in

		2g)
			ssid='IMZLY-2G'
		;;

		5g)
			ssid='IMZLY-5G'
		;;

		*)
			# GL-MT6000 正常只会进入 2.4G / 5G
			# 如果未来配置结构发生变化，
			# 未识别频段使用基础名称。
			ssid='IMZLY'
		;;

	esac


	# 设置 WiFi 名称
	uci -q set wireless.$iface.ssid="$ssid"


	# WPA2-PSK + AES/CCMP
	#
	# LuCI 中对应：
	# WPA2-PSK（强安全性）
	uci -q set wireless.$iface.encryption='psk2+ccmp'


	# 设置 WiFi 密码
	uci -q set wireless.$iface.key="$WIFI_KEY"


	# 启用无线接口
	uci -q delete wireless.$iface.disabled
}


# ============================================================
# 应用无线配置
# ============================================================

config_load wireless


config_foreach \
	set_radio \
	wifi-device


config_foreach \
	set_iface \
	wifi-iface


uci -q commit wireless


exit 0
