# SPDX-License-Identifier: MIT
# Copyright (C) 2026 VIKINGYFY

name: MT6000

on:
  # 每天北京时间凌晨 03:00
  schedule:
    - cron: '0 19 * * *'

  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动追加插件包，多个请用\n符号隔开。'
        required: false
        type: string

      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: false
        required: false
        type: boolean

permissions: write-all

# ============================================================
# 防止定时编译和手动编译同时运行
#
# 后来的任务排队等待
# 不取消正在运行的任务
# 防止同时操作 Cache / Release
# ============================================================

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  config:
    name: MT6000

    uses: ./.github/workflows/WRT-CORE.yml

    with:
      WRT_CONFIG: MT6000
      WRT_THEME: argon

      WRT_NAME: GLMT6000_28

      WRT_SSID: MT6000
      WRT_WORD: ljx2026@.

      WRT_IP: 192.168.28.1
      WRT_PW: admin

      WRT_REPO: https://github.com/immortalwrt/immortalwrt.git
      WRT_BRANCH: openwrt-25.12
      WRT_SOURCE: immortalwrt/immortalwrt

      WRT_PACKAGE: ${{ inputs.PACKAGE }}
      WRT_TEST: ${{ inputs.TEST }}
